version: '3.7'

networks:
  common-net:
    external: true

services:
  app:
    build:
      target: ${DOCKER_BUILD_MODE}
    volumes:
      - ${DOCKER_VOLUME_CODES_ROOT_DIR}:/usr/src/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - common-net
