# .air.toml

# Set the root directory of your project
root = "."
tmp_dir = "storage/tmp"

# Directory to watch for changes
include = [
    "cmd/main",  # Watch the main package directory
]

# Exclude directories from watching
exclude = [
    ".git",
    "vendor",
    "storage"
]

# Command to build your application
[build]
cmd = "go build -o ./storage/tmp/main cmd/main/main.go"

bin = "./storage/tmp/main"
# Command to run your application
# [run]
# exec = "./storage/tmp/main"